language: php

php:

  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
- composer install --dev --no-interaction

script:
- mkdir -p build/logs
- phpunit --coverage-clover build/logs/clover.xml --bootstrap src/autoload.php tests/TextsTest.php

after_script:
  - php vendor/bin/coveralls
